### ISSUE TITLE
[Style Y074] change 1st reason

### ISSUE THREAD

**Issue by ddrabik** [johnpapa/angular-styleguide#316]
https://github.com/johnpapa/angular-styleguide#style-y074

 *Why?*: It makes sense.

 *Why?*: While we can allow the directive to be used as a class, if the directive is truly acting as an element it makes more sense as an element or at least as an attribute."

The 2nd reason provides more detail on how it makes sense, so the first reason isn't needed.
Should the 1st instead mention that classes and comment directives were intended for use with older browsers?

**Comment by wardbell** [comment]
"It makes sense" is not a real "Why" although it is funny.

I don't understand the second "Why". Can someone explain it?

And I neither understand nor agree that "classes and comment directives were intended for use with older browsers". The comment directive addressed a particular shortcoming with ngRepeat on <li> and <tr> elements which was subsequently addressed with options; I can be specific bit my point is that I don't think the were old browser concerns. Care to explain why you think otherwise?

**Comment by wardbell** [comment]
Aargh! The editor ate a part of my reply which should read: "shortcomings with ngRepeat on `<li>` and `<tr>` elements "

**Comment by ddrabik** [comment]
I had first heard the old browser concern from the [Adventures in Angular podcast](http://devchat.tv/adventures-in-angular/012-aia-directives) (5:24). The 3rd best practice in the [Matching Directives docs](https://docs.angularjs.org/guide/directive#matching-directives) also seemed like it was talking about older browsers. Does that DOM API limitation it is referring to still exist?

**Comment by johnpapa** [comment]
I'm fine updating this, if here is a suggestion make a PR.

@wardbell ... the second why is "While we can allow the directive to be used as a class, if the directive is truly acting as an element it makes more sense as an element or at least as an attribute."

If you find something to be clearer, go for it. i don't really have strong feelings over the wording so have at it.

**Comment by dietergeerts** [comment]
Personally I think that using directives as a class is a very bad idea. Just never do this. A directive is meant to be/do:

1. Alter or add to the behavior of an element, which is the reason to let the directive be used as an attribute, as attributes are extra behaviors on an element.
2. Have it's own logic as a component, so being an element as they are acting on their own, which is the reason to have it as an element.

It can't be more simpler and logical. I think that's why the initial 'it make sense' comes from as it just makes sense what to choose.

**Comment by johnpapa** [comment]
Interesting conversation, but I dont se any action coming from this.
